SET DEFINE OFF

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (11, '강아지 사료');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (21, '간식 - 껌');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (22, '간식 - 캔/통조림');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (23, '간식 - 육포사시미(대용량)');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (24, '간식 - 육포사시미(소용량)');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (25, '간식 - 소시지/습식간식');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (31, '목욕용품 - 타올/기타');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (32, '목욕용품 - 샴푸린스 겸용');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (33, '목욕용품 - 샴푸');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (41, '종합영양제');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (51, '위생배변패드 - 배변판/패드');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (52, '위생배변패드 - 기저귀/팬티');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (61, '급식기/급수기');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (62, '쌍수기');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (63, '사료 보관통');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (71, '고양이 사료');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (81, '고양이 간식 - 스낵, 드롭스');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (82, '고양이 간식 - 통살, 닭가슴살');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (91, '고양이 용품 - 모래');

INSERT INTO CATEGORY (CATEGORYID, CATEGORYNAME) 
VALUES (92, '고양이 용품 - 화장실');

